name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Every Saturday at 4:30 AM UTC.
    - cron:  '30 4 * * 6'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:
    # Don't run for self-PR's.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, macos-26, macos-15, macos-14]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Update Rust Toolchain
      run: rustup update
    - name: Install dependencies (macOS)
      run: |
        brew untap aws/tap
        brew install shunit2 shellcheck shfmt
      if: runner.os == 'macOS'
    - name: Install dependencies (Linux)
      run: |
        sudo apt-get update
        sudo apt-get -y install libacl1-dev acl shunit2 shellcheck valgrind
      if: runner.os == 'Linux'
    - name: Fetch
      run: cargo fetch
    - name: Build (no-serde)
      run: cargo build
    - name: Build (serde)
      run: cargo build --features serde
    - name: Unit Test (no-serde)
      run: RUST_LOG=debug cargo test
    - name: Unit Test (serde)
      run: RUST_LOG=debug cargo test --features serde,_LABTEST
    - name: Run integration tests
      run: ./tests/run_tests.sh
    - name: Run memory tests
      run: ./tests/run_tests.sh memcheck
      # macos-15: Leaks check seems to hang final 'Complete job' step in Github action?
      if: matrix.os != 'macos-15'
    - name: Run TMPFS tests (Linux)
      run: |
        mkdir /run/user/$UID/exacl
        export TMPDIR=/run/user/$UID/exacl
        RUST_LOG=debug cargo test --features serde
        ./tests/run_tests.sh
      if: runner.os == 'Linux'
    - name: Code coverage
      env:
        CODECOV_TOKEN: ${{ secrets.EXACL_CODECOV_TOKEN }}
      run: ./ci/coverage.sh codecov
    - name: Lint Check
      run: ./ci/lint.sh
    - name: Format Check
      run: ./ci/format.sh
    - name: Docs Check
      run: ./ci/docs.sh
    - name: Bindgen Check
      run: ./ci/bindgen.sh

  build-ubuntu-26-04:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ubuntu:26.04
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Install dependencies (Linux)
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        # Need `libclang-dev` for bindgen.
        apt-get -y install curl build-essential libacl1-dev libclang-dev acl shunit2 shellcheck
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Fetch
      run: cargo fetch
    - name: Build (no-serde)
      run: cargo build
    - name: Build (serde)
      run: cargo build --features serde
    - name: Unit Test (no-serde)
      run: RUST_LOG=debug cargo test
    - name: Unit Test (serde)
      run: RUST_LOG=debug cargo test --features serde,_LABTEST
    - name: Run integration tests
      run:  setpriv --reuid=1001 --regid=1001 --clear-groups ./tests/run_tests.sh
    - name: Lint Check
      run: ./ci/lint.sh
    - name: Format Check
      run: ./ci/format.sh
    - name: Docs Check
      run: ./ci/docs.sh
    - name: Bindgen Check
      run: ./ci/bindgen.sh

  build-freebsd:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: ["15.1", "15.0", "14.4"]
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Run Tests
      uses: vmactions/freebsd-vm@77ed28d336d03fe19a3f4f7266c1d2c4714dd79d # v1.5.2
      with:
        release: "${{matrix.release}}"
        usesh: true
        copyback: false
        prepare: |
          # Record info about the test environment.
          mount
          df -h
          sysctl hw.model hw.ncpu hw.physmem
          freebsd-version
          # Create a 5 MB memory based FS with acls enabled and
          # mount it to a sub-directory of /tmp (where it won't
          # interfere with other uses of /tmp.)
          mkdir /tmp/exacl_acls /tmp/exacl_nfsv4acls
          mdmfs -o acls -s 5m md /tmp/exacl_acls
          mdmfs -o nfsv4acls -s 5m md /tmp/exacl_nfsv4acls
          mount
          env
          # Install Rust.
          pkg install -y bash curl llvm15
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          # Install shunit2.
          mkdir -p /tmp/bin
          curl https://raw.githubusercontent.com/kward/shunit2/master/shunit2 -sSf --output /tmp/bin/shunit2
          chmod ugo+x /tmp/bin/shunit2
        run: |
          . $HOME/.cargo/env
          # Set up path for shunit2.
          export PATH="$PATH:/tmp/bin"
          cargo fetch
          cargo build   # Build no-serde
          cargo build --features serde   # Build with serde
          cargo test --no-run --features serde  # Compile only
          # Run tests on our mem-based FS with acls.
          export TMPDIR=/tmp/exacl_acls
          echo "*** TMPDIR=$TMPDIR"
          RUST_LOG=debug cargo test --features serde,_LABTEST
          ./tests/run_tests.sh
          export TMPDIR=/tmp/exacl_nfsv4acls
          echo "*** TMPDIR=$TMPDIR"
          RUST_LOG=debug cargo test --features serde,_LABTEST
          ./tests/run_tests.sh
          export TMPDIR=/tmp
          echo "*** TMPDIR=$TMPDIR"
          ./ci/bindgen.sh
          ./ci/lint.sh
