name: Docs

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  publish-docs:

    permissions:
      contents: write  # for peaceiris/actions-gh-pages to push pages branch
    runs-on: ubuntu-20.04

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Install dependencies (Linux)
      run: sudo apt-get -y install libacl1-dev
    - name: Build Docs
      run: ./ci/docs.sh
    - name: Publish Docs to Github Pages
      uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
