name: Publish

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:

  publish-crate:
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Install dependencies (Linux)
      run: sudo apt-get -y install libacl1-dev
    - name: Publish Crate
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
      run: cargo publish
