name: Publish

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:

  publish-crate:
    runs-on: ubuntu-20.04

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Install dependencies (Linux)
      run: sudo apt-get -y install libacl1-dev
    - name: Publish Crate
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
      run: cargo publish
